server:
  http_listen_port: 3100

ingester:
  wal:
    dir: /loki/wal
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s

# ingester:
#   wal:
#     dir: /tmp/loki/wal
#   chunk_idle_period: 5m
#   chunk_target_size: 1048576
#   max_chunk_age: 1h
#   # Removed `max_cache_size` as it's unsupported

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache
    # Removed `shared_store` as it's unsupported

  filesystem:
    directory: /tmp/loki/chunks

compactor:
  working_directory: /tmp/loki/compactor
  # Removed `shared_store`, `retention_deletes_enabled`, and `retention_duration` as they are unsupported

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

query_range:
  # Removed `per_query_timeout` as it's unsupported
  max_retries: 5

# Query frontend config (optional, if you're using frontend queries)
# frontend:
#   enabled: true
#   tail_proxy_url: "http://localhost:3100"

schema_config:
  configs:
    - from: 2022-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: loki_index_
        period: 24h
