global:
  scrape_interval: 15s  # The interval at which Prometheus scrapes metrics.

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']  # Target your OpenTelemetry Collector for OTLP metrics (adjust as needed).

  - job_name: "otel-js-app"
    static_configs:
      - targets: ["otel-js-app:5000"]
      
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Scraping Prometheus itself for health and metrics.
      
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']  # Scrape Loki metrics if needed